


CREATE view [dbo].[V1644_SMUSER] as
SELECT        'RRC' AS FCOMPANYCD, StaffID AS FUSERCD, '1900/01/01' AS FVALIDYMD, 
t2.FBUSHOCD AS FTANTOCD,
'rrc123456' AS FPASSWORD,'ALL' as FMENUGID, '2999/12/31' AS FINVALYMD, 1 AS FTUKACD, 1 AS FUPDBUMON, 1 AS FREFBUMON
FROM            rrc_database.dbo.[222_Staff] t1
left join [V2151_SMBUSHO_P] t2
on t1.SecID = t2.FJOIBUSHOCD COLLATE DATABASE_DEFAULT
inner join SMUSERMEI t3 
on t1.StaffID=t3.[FUSERCD] COLLATE DATABASE_DEFAULT
WHERE        (SecID <> '9999') AND (StaffID NOT LIKE '9%') AND (StaffID NOT LIKE '*%')  AND (StaffID NOT LIKE '%H%') AND (StaffID NOT LIKE '%r%') AND (StaffID not in ('0001','0000')) AND (StaffID NOT LIKE '%P%')   
