/****** Script for SelectTopNRows command from SSMS  ******/
create view V1644_SMSHONINKENSHA as 
SELECT [FCOMPANYCD]
      ,[FSHONINKB]
      ,[FKIANBUSHOCD]
      ,[FSHONINBUSHOCD]
      ,[FSHONINSHACD]
      ,Format([FVALIDYMD],'yyyy/MM/dd') as [FVALIDYMD]
      ,[FSHONINMINGAK]
      ,[FSHONINMAXGAK]
      ,[FDAIRICD]
      ,[FDAIRICD2]
      ,[FDAIRICD3]
      ,[FDAIRICD4]
      ,[FDAIRICD5]
      , Format([FINVALYMD],'yyyy/MM/dd') as [FINVALYMD]
      ,[FENTDT]
      ,[FENTPRG]
      ,[FENTUSR]
      ,[FUPDTEDT]
      ,[FUPDTEPRG]
      ,[FUPDTEUSR]
  FROM [scaw_db].[dbo].[SMSHONINKENSHA]