
CREATE VIEW [dbo].[V2151_SMKOJUN]
AS
WITH TB1 AS (SELECT DISTINCT FKOJUNHINCD FROM V2151_SMKOJUN_Temp)
   , TB2 AS (SELECT T1.FHINCD
		     FROM SMHIN AS T1
		     LEFT JOIN TB1
		     ON T1.FHINCD = TB1.FKOJUNHINCD
		     WHERE T1.FHINTYP = 'M'
		     AND TB1.FKOJUNHINCD IS NULL)

SELECT * FROM [V2151_SMKOJUN_Temp]

UNION ALL

SELECT 'RRC' AS FCOMPANYCD
	, FHINCD AS FKOJUNHINCD
	, 'RRC' AS FKYOTENCD
	, '*' AS FSEZOPTCD
	, '010' AS FKOJUN
	, 'M' AS FKOJUNTYP
	, 'OTHR' AS FKOTEICD
	, 'OTHR' AS FSAGYOCD
	, 1 AS [FKOJUNLT]
	, 0 AS [FOFFSET]
	, 1 AS [FTOKKYUKOJUNLT]
	, 0 AS [FTOKKYUOFFSET]
	, 0 AS [FJIGUFLG]
	, '' AS [FJIGUNO]
FROM TB2
