
CREATE VIEW [dbo].[V2151_SMZUMEN]
AS
SELECT  'RRC' AS FCOMPANYCD
	, TRIM(ITHNBN) AS FHINCD
	, TRIM(ITHNBN) AS FZUMENNO
	, '1900/01/01' AS FVALIDYMD
	, '2999/12/31' AS FINVALYMD
	, '' AS FBIKO
	, 1 AS FSHUZUMENFLG
	, '' AS FZUCHUNO
	, '' AS FZUHAN, N'\\192.168.0.5\Drawing\Print_PDF\' + TRIM(ITHNBN) + '.pdf' AS FDOCPATH
FROM                         OPENQUERY(AS400_MPUTEST, 'SELECT * FROM MPIT00')
WHERE                       (SUBSTRING(ITHNBN, 1, 2) IN ('1A', '2A', '3A', '4A', '*E', '*M'))
