CREATE VIEW [dbo].[V2151_SMBUSHO]
AS
WITH TB1
AS (
	SELECT 'RRC' AS FCOMPANYCD
		,Dept_Code AS FBUSHOCD
		,'en' AS FLNGKB
		,'1900-01-01' AS FVALIDYMD
		,'2999-12-31' AS FINVALYMD
		,'A' AS FBUSHOTYP
		,'' AS FKOKYAKUFLG
		,'' AS FSIREFLG
		,Dept_ShortName AS FBUSHORMEI
		,Dept_FullName AS FBUSHOMEI
		,'' AS FBUSHOKANAMEI
		,'' AS FJOIBUSHOCD
		,'AM' AS FSHOZOKUKB
		,'' AS FKUNICD
		,'' AS FSHOSYAKB
		,'' AS FKAZEIKB
		,'' AS FTUKACD
		,'' AS FJUSHO1
		,'' AS FFAXNO
		,'' AS FMAIL1
		,'' AS FTAXCODE
		,'' AS FSIHARAISAKICD
		,'' AS FSIHARAIGAKHASUSHORIKB
		,'' AS FFAXSENDKB1
	FROM dbo.[2151_Department] AS T1
	
	UNION ALL
	
	SELECT 'RRC' AS FCOMPANYCD
		,Group_Code AS FBUSHOCD
		,'en' AS FLNGKB
		,'1900-01-01' AS FVALIDYMD
		,'2999-12-31' AS FINVALYMD
		,'M' AS FBUSHOTYP
		,0 AS FKOKYAKUFLG
		,0 AS FSIREFLG
		,Group_ShortName AS FBUSHORMEI
		,Group_FullName AS FBUSHOMEI
		,ISNULL(Group_Katahana,'') AS FBUSHOKANAMEI
		,FJOIBUSHOCD
		,FSHOZOKUKB
		,'' AS FKUNICD
		,'' AS FSHOSYAKB
		,'' AS FKAZEIKB
		,'' AS FTUKACD
		,'' AS FJUSHO1
		,'' AS FFAXNO
		,'' AS FMAIL1
		,'' AS FTAXCODE
		,'' AS FSIHARAISAKICD
		,'' AS FSIHARAIGAKHASUSHORIKB
		,'' AS FFAXSENDKB1
	FROM dbo.[2151_Group] AS T1
	
	UNION ALL
	
	SELECT 'RRC' AS FCOMPANYCD
		,Manager AS FBUSHOCD
		,'en' AS FLNGKB
		,'1900-01-01' AS FVALIDYMD
		,'2999-12-31' AS FINVALYMD
		,'P' AS FBUSHOTYP
		,'' AS FKOKYAKUFLG
		,'' AS FSIREFLG
		,T2.StaffName AS FBUSHORMEI
		,T2.StaffName AS FBUSHOMEI
		,'' AS FBUSHOKANAMEI
		,Dept_Code AS FJOIBUSHOCD
		,'PM' AS FSHOZOKUKB
		,'' AS FKUNICD
		,'' AS FSHOSYAKB
		,'' AS FKAZEIKB
		,'' AS FTUKACD
		,'' AS FJUSHO1
		,'' AS FFAXNO
		,LOWER(TRIM(EmailSoft)) AS FMAIL1
		,'' AS FTAXCODE
		,'' AS FSIHARAISAKICD
		,'' AS FSIHARAIGAKHASUSHORIKB
		,'' AS FFAXSENDKB1
	FROM dbo.[2151_Department] AS T1
	LEFT JOIN rrc_database.dbo.[222_Staff] AS T2 ON T1.Manager = T2.StaffID
	
	UNION ALL
	
	SELECT 'RRC' AS FCOMPANYCD
		,Customer_Code AS FBUSHOCD
		,'en' AS FLNGKB
		,'1900-01-01' AS FVALIDYMD
		,'2999-12-31' AS FINVALYMD
		,'C' AS FBUSHOTYP
		,1 AS FKOKYAKUFLG
		,0 AS FSIREFLG
		,ISNULL(Customer_ShortName,'') AS FBUSHORMEI
		,ISNULL(Customer_FullName,'') AS FBUSHOMEI
		,'' AS FBUSHOKANAMEI
		,'' AS FJOIBUSHOCD
		,'' AS FSHOZOKUKB
		,FKUNICD
		,0 AS FSHOSYAKB
		,FKAZEIKB
		,Currency AS FTUKACD
		,ISNULL(Address,'') AS FJUSHO1
		,Fax AS FFAXNO
		,ISNULL(Mail,'') AS FMAIL1
		,Tax AS FTAXCODE
		,'0241' AS FSIHARAISAKICD
		,'0' AS FSIHARAIGAKHASUSHORIKB
		,'3' AS FFAXSENDKB1
	FROM dbo.[2151_Customer] AS T1
	
	UNION ALL
	
	SELECT 'RRC' AS FCOMPANYCD
		,Supplier_Code COLLATE DATABASE_DEFAULT AS FBUSHOCD
		,'en' AS FLNGKB
		,'1900-01-01' AS FVALIDYMD
		,'2999-12-31' AS FINVALYMD
		,'C' AS FBUSHOTYP
		,0 AS FKOKYAKUFLG
		,1 AS FSIREFLG
		,ISNULL(Supplier_ShortName,'') COLLATE DATABASE_DEFAULT AS FBUSHORMEI
		,Supplier_FullName COLLATE DATABASE_DEFAULT AS FBUSHOMEI
		,ISNULL(Supplier_Katahana,'') COLLATE DATABASE_DEFAULT AS FBUSHOKANAMEI
		,'' AS FJOIBUSHOCD
		,'' AS FSHOZOKUKB
		,Country_Code COLLATE DATABASE_DEFAULT AS FKUNICD
		,'' AS FSHOSYAKB
		,'' AS FKAZEIKB
		,Currency COLLATE DATABASE_DEFAULT AS FTUKACD
		,ISNULL([Address],'') COLLATE DATABASE_DEFAULT AS FJUSHO1
		,ISNULL(FAX,'') COLLATE DATABASE_DEFAULT AS FFAXNO
		,ISNULL(PICEMAIL,'') COLLATE DATABASE_DEFAULT AS FMAIL1
		,'' AS FTAXCODE
		,'' AS FSIHARAISAKICD
		,'' AS FSIHARAIGAKHASUSHORIKB
		,'' AS FFAXSENDKB1
	FROM [scaw_db].[dbo].[2151_Supplier]
	)
SELECT FCOMPANYCD
	,FBUSHOCD
	,FLNGKB
	,FVALIDYMD
	,FINVALYMD
	,FBUSHOTYP
	,FKOKYAKUFLG
	,FSIREFLG
	,FBUSHORMEI
	,FBUSHOMEI
	,FBUSHOKANAMEI
	,FJOIBUSHOCD
	,FSHOZOKUKB
	,FKUNICD
	,'' AS FAREACD
	,'' AS FDEFKOJUNLT
	,'' AS FZCD
	,'' AS FHOKANCD
	,'' AS FKANRENFLG
	,'' AS FBODYKAKERITU
	,'' AS FSERVICEKAKERITU
	,'' AS FETCKAKERITU
	,'' AS FSIKIRIRITU
	,FSHOSYAKB
	,'' AS FGYOSHUKB
	,FKAZEIKB
	,'' AS FYOSINSAKICD
	,FTUKACD
	,'' AS FYOSINGENDO
	,'' AS FUKEWATASICD
	,'' AS FSIHARAICD
	,'' AS FSIHARAISIMECD
	,'' AS FKISANCD
	,'' AS FTEGATAFURIDASICD
	,'' AS FFURIKOMICD
	,'' AS FSITE
	,'' AS FBIKO
	,'' AS FKOTEISEKININCD
	,'' AS FKIANTANTOKB
	,'' AS FANKNITKB
	,'' AS FSTRANKNITPNT
	,'' AS FENDANKNITPNT
	,'' AS FSITAUKEFLG
	,'' AS FSEIKYUSAKICD
	,'' AS FSEKYUZEISHORIKB
	,'' AS FSEKYUKB
	,'' AS FSEKYUSIME1
	,'' AS FSEKYUSIME2
	,'' AS FSEKYUSIME3
	,'' AS FSEKYUZEIKEISANKB
	,'' AS FSEKYUGAKHASUSHORIKB
	,'' AS FSEKYUZEIHASUSHORIKB
	,FSIHARAISAKICD
	,'' AS FSIHARAIZEIKB
	,'' AS FSIHARAIZEISHORIKB
	,'' AS FSIHARAISIME1
	,'' AS FSIHARAISIME2
	,'' AS FSIHARAISIME3
	,'' AS FSIHARAIZEIKEISANKB
	,FSIHARAIGAKHASUSHORIKB
	,'' AS FSIHARAIZEIHASUSHORIKB
	,'' AS FFACTSIHARAICD
	,'' AS FSKOZACD
	,'' AS FTGSKOZACD
	,'' AS FTESUFUTANKB
	,'' AS FSIHARAISHORIKB
	,'' AS FSIHARAIKYUJITSUSYORIKB
	,'' AS FSIHARAITUKIMKB
	,'' AS FSIHARAIHOHO
	,'' AS FSIHARAIJOKENKB
	,'' AS FUSKB
	,'' AS FSIHARAIJOKENGAK
	,'' AS FSIHARAIJOKENLS
	,'' AS FSIHARAITUKI1DAI
	,'' AS FSIHARAIYMD1DAI
	,'' AS FSIHARAITYP1DAI
	,'' AS FSIHARAISITENISSU1DAI
	,'' AS FSIHARAISITETUKISU1DAI
	,'' AS FSIHARAISITEDAY1DAI
	,'' AS FSIHARAIRITSU1DAI
	,'' AS FSIHARAITUKI2DAI
	,'' AS FSIHARAIYMD2DAI
	,'' AS FSIHARAITYP2DAI
	,'' AS FSIHARAISITENISSU2DAI
	,'' AS FSIHARAISITETUKISU2DAI
	,'' AS FSIHARAISITEDAY2DAI
	,'' AS FSIHARAIRITSU2DAI
	,'' AS FSIHARAITUKI3DAI
	,'' AS FSIHARAIYMD3DAI
	,'' AS FSIHARAITYP3DAI
	,'' AS FSIHARAISITENISSU3DAI
	,'' AS FSIHARAISITETUKISU3DAI
	,'' AS FSIHARAISITEDAY3DAI
	,'' AS FSIHARAIRITSU3DAI
	,'' AS FSIHARAITUKI1BUN
	,'' AS FSIHARAIYMD1BUN
	,'' AS FSIHARAITYP1BUN
	,'' AS FSIHARAISITENISSU1BUN
	,'' AS FSIHARAISITETUKISU1BUN
	,'' AS FSIHARAISITEDAY1BUN
	,'' AS FSIHARAITUKI2BUN
	,'' AS FSIHARAIYMD2BUN
	,'' AS FSIHARAITYP2BUN
	,'' AS FSIHARAISITENISSU2BUN
	,'' AS FSIHARAISITETUKISU2BUN
	,'' AS FSIHARAISITEDAY2BUN
	,'' AS FSIHARAITUKI3BUN
	,'' AS FSIHARAIYMD3BUN
	,'' AS FSIHARAITYP3BUN
	,'' AS FSIHARAISITENISSU3BUN
	,'' AS FSIHARAISITETUKISU3BUN
	,'' AS FSIHARAISITEDAY3BUN
	,'' AS FKAIKAKEMIBARAIKB
	,'' AS FSHOKUTIKB
	,'' AS FTEGATAIFBUNKATUKB
	,'' AS FSIHARAITUTISHOFLG
	,'' AS FYUKOFLG
	,FFAXSENDKB1
	,'' AS FFAXSENDKB2
	,'' AS FTEIKAKAKERITU
	,'' AS FFURIKOMININMEI
	,'' AS FRANK
	,'RRC' AS FEIGYOBUMON
	,'en' AS FSIYOLNGKB
	,'' AS FSHUKEIBUMONFLG
	,'' AS FSHUKKACOLUMNMEI
	,'' AS FSHUKKAHYOJINAIYO
	,FTAXCODE
	,'' AS FKAISYUJOKENKB
	,'' AS FKAISYUMONTH1
	,'' AS FKAISYUDAY1
	,'' AS FKAISYUMONTH2
	,'' AS FKAISYUDAY2
	,'' AS FKYUJITSUSYORIKB
	,'' AS FKAISYUJOKENKIN
	,'' AS FKAISYUJOKEN
	,'' AS FHIRITSU
	,'' AS FNYUKINTYP1
	,'' AS FNYUKINTYP2
	,'' AS FSITE2
	,'' AS FKAISHUTUKIMKB
	,'' AS FSITETUKISU
	,'' AS FSITEDAY
	,'' AS FSITETUKISU2
	,'' AS FSITEDAY2
	,'' AS FSOSAISAKICD
	,0 AS FSOSAIFLG
	,0 AS FANKENPOINT
	,1 AS FSTTFLG
	,1 AS FENDFLG
	,'RRC' AS FKYOTENCD
	,'' AS FTAXCD
	,'' AS FTXTYOBI01
	,'' AS FTXTYOBI02
	,'' AS FTXTYOBI03
	,'' AS FFREECD1
	,'' AS FFREECD2
	,'' AS FFREECD3
	,'' AS FYUBINNO
	,FJUSHO1
	,'' AS FJUSHO2
	,'' AS FJUSHO3
	,'' AS FTELNO
	,'' AS FTANTOCD
	,FFAXNO
	,'' AS FFAXNO2
	,'' AS FFAXNO3
	,FMAIL1
	,'' AS FMAIL2
	,'' AS FMAIL3

	,'' AS FTOKUSOKUFLG
	,'' AS FBOEKIJOKEN
	,'' AS FSHIHARAIJOKEN1
	,'' AS FSHIHARAIJOKEN2
FROM TB1