CREATE VIEW [dbo].[V2151_SMBUSHO_M]
AS
SELECT 'RRC' AS FCOMPANYCD
	,TRIM(UPPER(OptionID)) AS FBUSHOCD
	,'en' AS FLNGKB
	,'1900/01/01' AS FVALIDYMD
	,'2999/12/31' AS FINVALYMD
		
	,'M' AS FBUSHOTYP
	,OptionID AS FBUSHORMEI
	,OptName AS FBUSHOMEI
	,'*' AS FBUSHOKANAMEI
	,'' AS FJOIBUSHOCD
		
	,'MK' AS FSHOZOKUKB
	,1 AS FANKENPOINT
	,1 AS FSTTFLG
	,1 AS FENDFLG
FROM [rrc_database].[dbo].[242_option] AS T1

UNION ALL

SELECT 'RRC' AS FCOMPANYCD
	,TRIM(UPPER(T1.WorkType)) AS FBUSHOCD
	,'en' AS FLNGKB
	,'1900/01/01' AS FVALIDYMD
	,'2999/12/31' AS FINVALYMD
		
	,'M' AS FBUSHOTYP
	,T1.WorkType AS FBUSHORMEI
	,T1.WorkType AS FBUSHOMEI
	,'*' AS FBUSHOKANAMEI
	,'' AS FJOIBUSHOCD
		
	,'MK' AS FSHOZOKUKB
	,1 AS FANKENPOINT
	,1 AS FSTTFLG
	,1 AS FENDFLG
FROM (	SELECT DISTINCT WorkType FROM [rrc_database].[dbo].[231_TimeWork]
		WHERE ISNULL(WorkType,'') != '') AS T1