
CREATE VIEW [dbo].[V2151_SMTANKAHD]
AS
SELECT FCOMPANYCD
	, FTORIHIKIKB
	, FHINCD
	, FKYOTENCD
	, FTORIHIKICD
	, ISNULL(FSAGYOCD,'OTHR') AS FSAGYOCD
	, FYOTEISAGYOHOUR
	, FKOJUNLT
	, FTOKKYUKOJUNLT
	, FBIKO
FROM [V2151_SMTANKAHD_Root]