CREATE VIEW [dbo].[V2151_SMBUSHO_P]
AS

--SELECT 'RRC' AS FCOMPANYCD
--	,Manager AS FBUSHOCD
--	,'en' AS FLNGKB
--	,'1900/01/01' AS FVALIDYMD
--	,'2999/12/31' AS FINVALYMD
--	,'P' AS FBUSHOTYP
--	,TRIM(T2.StaffName) AS FBUSHORMEI
--	,TRIM(T2.StaffName) AS FBUSHOMEI
--	,'*' AS FBUSHOKANAMEI
--	,TRIM(Dept_Code) AS FJOIBUSHOCD
--	,'PM' AS FSHOZOKUKB
--	,'' AS FYUBINNO
--	,'' AS FJUSHO1
--	,'' AS FJUSHO2
--	,'' AS FJUSHO3
--	,'' AS FTELNO
--	,'' AS FBIKO
--	,'' AS FFAXNO
--	,'' AS FFAXNO2
--	,'' AS FFAXNO3
--	,LOWER(TRIM(EmailSoft)) AS FMAIL1
--	,'' AS FMAIL2
--	,'' AS FMAIL3
--FROM dbo.[2151_Department] AS T1
--LEFT JOIN rrc_database.dbo.[222_Staff] AS T2 ON T1.Manager = T2.StaffID




SELECT 'RRC' AS FCOMPANYCD
	,T1.FSIGENCD AS FBUSHOCD
	,'en' AS FLNGKB
	,'1900/01/01' AS FVALIDYMD
	,'2999/12/31' AS FINVALYMD
	,'P' AS FBUSHOTYP
	,TRIM(FSIGENMEI) AS FBUSHORMEI
	,TRIM(FSIGENMEI) AS FBUSHOMEI
	,'*' AS FBUSHOKANAMEI
	,TRIM(FSIGENCLASSCD) AS FJOIBUSHOCD
	,T2.FSHOZOKUKB
	,'' AS FYUBINNO
	,'' AS FJUSHO1
	,'' AS FJUSHO2
	,'' AS FJUSHO3
	,'' AS FTELNO
	,'' AS FBIKO
	,'' AS FFAXNO
	,'' AS FFAXNO2
	,'' AS FFAXNO3
	,LOWER(TRIM(T3.EmailSoft)) AS FMAIL1
	,'' AS FMAIL2
	,'' AS FMAIL3
FROM V_SMSIGEN AS T1
LEFT JOIN dbo.[2151_Department] AS T2
ON T1.FSIGENCLASSCD = T2.Dept_Code COLLATE DATABASE_DEFAULT 
LEFT JOIN rrc_database.dbo.[222_Staff] AS T3 
ON T1.FSIGENCD = T3.StaffID COLLATE DATABASE_DEFAULT 
WHERE TRIM(ISNULL(T1.FTANTOCD,'')) !=''