CREATE VIEW [dbo].[V2151_SMTANKADTL]
AS
WITH TB1 AS (SELECT ROW_NUMBER() OVER (PARTITION BY MIHNBN, MISICD  ORDER BY MIHNBN, MISRYO) AS RN1
					, ROW_NUMBER() OVER (PARTITION BY MIHNBN, MISICD  ORDER BY MIHNBN, MISRYO) + 1 AS RN2
					, MIHNBN, MISICD, MISRYO, MITDTE, MITANK, ITLDTM, ITHNTP, CURRENCY
			 FROM OPENQUERY(AS400_MPUTEST, 'WITH TB1 AS (	SELECT  MIHNBN, MISICD, MISRYO, MITDTE, MITANK, T1.ITLDTM  
																, CASE WHEN T1.ITHNTP = ''P'' AND T2.ITHNTP = ''M'' THEN ''M''
																  ELSE T1.ITHNTP END AS ITHNTP 
																, SUBSTRING(GAFILL,43,1) AS CURRENCY
															FROM MPMI00 
															INNER JOIN MPIT00 AS T1
															ON T1.ITHNBN = MIHNBN AND T1.ITSICD = MISICD
															LEFT JOIN MPIT00 AS T2
															ON T1.ITSHBN = T2.ITHNBN
															LEFT JOIN MPGA00 AS T3
															ON GASICD = MISICD
															WHERE MITANK > 0 AND T1.ITHNTP != ''F'')
											SELECT MIHNBN, MISICD, MISRYO, MITDTE, MITANK, ITLDTM, ITHNTP, 
												CASE WHEN CURRENCY = ''D'' THEN ''VND'' 
 	 												 WHEN CURRENCY = ''W'' THEN ''KRW'' 
 													 WHEN CURRENCY = ''E'' THEN ''EUR'' 
	 												 WHEN CURRENCY = ''S'' THEN ''SGD''
 													 WHEN CURRENCY = ''B'' THEN ''THB'' 
	 												 ELSE ''JPY'' 		
												END	AS CURRENCY
											FROM TB1')) 
	 , TB2 AS (SELECT T1.MIHNBN, T1.MISICD, ISNULL(T2.MISRYO,0) + 1 AS MISRYO , T1.MITDTE, T1.MITANK, T1.ITLDTM, T1.ITHNTP AS PartType, T1.Currency
			 FROM TB1 AS T1
			 LEFT JOIN TB1 AS T2
			 ON T1.MIHNBN = T2.MIHNBN AND T1.MISICD = T2.MISICD AND T1.RN1 = T2.RN2) 
SELECT 'RRC' AS FCOMPANYCD
		,  CASE WHEN PartType = 'M' THEN 2
				WHEN PartType IN ('S','P') THEN 1
					END AS FTORIHIKIKB
		, ISNULL(DummyPart,TRIM(MIHNBN)) AS FHINCD
		, 'RRC' AS FKYOTENCD
		, ISNULL(FBUSHOCD,'B00000') AS FTORIHIKICD
		, ISNULL(T2.FSAGYOCD,'******') AS FSAGYOCD
		, CASE WHEN MISRYO = 9999999 THEN 999999
		  ELSE  MISRYO END AS FMINSU 
		,CASE WHEN ISDATE(MITDTE) = 1 THEN FORMAT(CONVERT(Date, CAST(MITDTE AS nvarchar(8))),'yyyy/MM/dd') 
			  ELSE '1990/01/01' END AS FVALIDYMD
		, MITANK AS FTANKA
		, TB2.Currency AS FTUKACD
		, 0 AS FTANKAKB
		, '2999/12/31' AS FINVALYMD
		, CASE WHEN ITLDTM = 0 THEN 1 ELSE ITLDTM END AS FLT
		, '' AS FKOBAIMITUNO
FROM TB2
LEFT JOIN [SMHINDUMMY]
ON DSPartNo COLLATE DATABASE_DEFAULT = TRIM(MIHNBN)
LEFT JOIN [V2151_SMBUSHO_C_Supplier] 
ON MISICD = FBUSHOCD COLLATE DATABASE_DEFAULT 
LEFT JOIN [V2151_SMTANKAHD] AS T2
ON MIHNBN = T2.FHINCD 