
CREATE VIEW [dbo].[V2151_SMTANKAHD_Root]
AS
WITH TB1 AS (	SELECT 'RRC' AS FCOMPANYCD
					, CASE WHEN PartType = 'M' THEN 2
						   WHEN PartType IN ('S','P') THEN 1
					  END AS FTORIHIKIKB
					, TRIM(PartNo) AS FHINCD
					, 'RRC' AS FKYOTENCD
					, SupplierID AS FTORIHIKICD
					, CASE WHEN PartType IN ('S','P') THEN '******' END AS FSAGYOCD
					, '' AS FYOTEISAGYOHOUR
					, '' AS FKOJUNLT
					, '' AS FTOKKYUKOJUNLT
					, Remark AS FBIKO     
				FROM OPENQUERY(AS400_MPUTEST,'WITH TB1 AS (	SELECT  DISTINCT MIHNBN, MISICD
									, CASE WHEN T1.ITHNTP = ''P'' AND T2.ITHNTP = ''M'' THEN ''M''
									 ELSE T1.ITHNTP END AS ITHNTP
									, T1.ITBICO
									, SUBSTRING(T1.ITFILL, 16, 4) AS ITFILL
								FROM MPMI00 
								INNER JOIN MPIT00 AS T1
								ON T1.ITHNBN = MIHNBN AND T1.ITSICD = MISICD
								LEFT JOIN MPIT00 AS T2
								ON T1.ITSHBN = T2.ITHNBN
								WHERE MITANK > 0 AND T1.ITHNTP != ''F'')
				SELECT MIHNBN AS PartNo
					, MISICD AS SupplierID
					, CASE WHEN ITHNTP = ''P'' AND ITFILL = ''0242'' THEN ''S''
					  ELSE ITHNTP END AS PartType
					, SUBSTRING(TRIM(ITBICO),1,100) AS Remark
				FROM TB1'))
SELECT TB1.FCOMPANYCD
	, TB1.FTORIHIKIKB
	, TB1.FHINCD
	, TB1.FKYOTENCD
	, TB1.FTORIHIKICD
	, ISNULL(TB1.FSAGYOCD, T2.FSAGYOCD) AS FSAGYOCD 
	, TB1.FYOTEISAGYOHOUR
	, TB1.FKOJUNLT
	, TB1.FTOKKYUKOJUNLT
	, TB1.FBIKO
FROM TB1
LEFT JOIN (	SELECT ROW_NUMBER() OVER (PARTITION BY FKOJUNHINCD ORDER BY FKOJUNHINCD, FSAGYOCD) AS RN
					, FKOJUNHINCD
					, FSAGYOCD
				FROM V2151_SMKOJUN) AS T2
ON TB1.FHINCD = T2.FKOJUNHINCD COLLATE DATABASE_DEFAULT AND T2.RN = 1
