


CREATE view [dbo].[V_SMSIGENKOSEI] AS 
with t01 as(
select * from [SMKOJUN] as t1 where t1.FKOTEICD in (select DISTINCT OptionID from rrc_database.dbo.[242_Option])),
TB1 AS(
select  
t01.FCOMPANYCD,
t01.FKOJUNHINCD,
t01.FKYOTENCD,
t01.FSEZOPTCD,
t01.FKOJUN,
t02.MachineID AS [FSIGENCD],
'1990/01/01' AS FVALIDYMD,
CASE WHEN t02.ProTime IS NULL THEN '' ELSE  t02.ProTime END AS FSTDHOUR,
'V' AS [FSAGYOKB],
'2999/12/31' as FINVALYMD,
'' as  FENTDT,
'' as FENTPRG,
'' as FENTUSR,
'' as FUPDTEDT,
'' as FUPDTEPRG,
'' as FUPDTEUSR



from t01
inner join(SELECT * FROM (SELECT PartID,T1.OptionID,ProTime,MachineID,ROW_NUMBER()OVER(PARTITION BY PartID,T1.OptionID,MachineID ORDER BY inputDate DESC) RN FROM [rrc_database].[dbo].[242_OptionData] T1 INNER JOIN [rrc_database].[dbo].[242_Option] T2 ON T1.OptionID = t2.OptionID)TT WHERE RN = 1) as t02 on t01.FKOJUNHINCD=t02.PartID and t01.FKOTEICD=t02.OptionID)

SELECT 
TB1.FCOMPANYCD,
TB1.FKOJUNHINCD,
TB1.FKYOTENCD,
TB1.FSEZOPTCD,
TB1.FKOJUN,
TB2.FSIGENCD,
TB1.FVALIDYMD,
TB1.FSTDHOUR,
TB1.[FSAGYOKB],
TB1.FINVALYMD,
TB1.FENTDT,
TB1.FENTPRG,
TB1.FENTUSR,
TB1.FUPDTEDT,
TB1.FUPDTEPRG,
TB1.FUPDTEUSR

FROM TB1 
left join [SMSIGEN] AS TB2 ON TB1.FSIGENCD=TB2.FSIGENMEI  WHERE  TB2.FSIGENCD IS NOT NULL
